-- Configuration values for the Perimeter system.
return {
  AL_DECAY_TURNS = 8,
  BORDER_TRIGGER_COOLDOWN = 5,
  CITY_BOMB_MIN_DELTA = 15,
  CITY_BOMB_COOLDOWN = 5,
  MAX_INTERCEPT_MOD_PER_CITY = 50,
  MOBILIZATION_HAPPINESS_PENALTY = 3,
  AUTO_MODE_LOCK_TURNS = 10,
  CRUISE_STRIKE_DAMAGE = 30,
  CYBERSTORM_DURATION = 2,
  CYBERSTORM_DEBUFFS = { production = -20, gold = -15, science = -10 },
  NETWORK_REQUIRED_NODES = 3,
  PROTOCOL_DELAY_IF_NO_ASSETS = true,
  ONLY_VS_AGGRESSOR = true,
  USE_CP_PROPERTIES_IF_AVAILABLE = true,
}
