-- Base buildings for the Perimeter network
INSERT INTO Buildings
  (Type, Description, Help, Cost, PrereqTech, NeverCapture, NukeImmune, BuildingClass)
VALUES
  ('BUILDING_RU_COMMAND_POST', 'TXT_KEY_BUILDING_RU_COMMAND_POST', 'TXT_KEY_BUILDING_RU_COMMAND_POST_HELP', 120, 'TECH_RADIO', 1, 0, 'BUILDINGCLASS_CONSTABLE'),
  ('BUILDING_RU_PROTECTED_LINK', 'TXT_KEY_BUILDING_RU_PROTECTED_LINK', 'TXT_KEY_BUILDING_RU_PROTECTED_LINK_HELP', 180, 'TECH_PLASTICS', 1, 1, 'BUILDINGCLASS_WIRE_SERVICE'),
  ('BUILDING_RU_EARLY_WARNING', 'TXT_KEY_BUILDING_RU_EARLY_WARNING', 'TXT_KEY_BUILDING_RU_EARLY_WARNING_HELP', 220, 'TECH_RADAR', 1, 1, 'BUILDINGCLASS_BOMB_SHELTER'),
  ('BUILDING_RU_SILO', 'TXT_KEY_BUILDING_RU_SILO', 'TXT_KEY_BUILDING_RU_SILO_HELP', 280, 'TECH_ROCKETRY', 1, 1, 'BUILDINGCLASS_MILITARY_BASE'),
  ('BUILDING_RU_COMPUTE_CENTER', 'TXT_KEY_BUILDING_RU_COMPUTE_CENTER', 'TXT_KEY_BUILDING_RU_COMPUTE_CENTER_HELP', 300, 'TECH_COMPUTERS', 1, 1, 'BUILDINGCLASS_LABORATORY'),
  ('BUILDING_RU_PERIMETER_NODE', 'TXT_KEY_BUILDING_RU_PERIMETER_NODE', 'TXT_KEY_BUILDING_RU_PERIMETER_NODE_HELP', 350, 'TECH_SATELLITES', 1, 1, 'BUILDINGCLASS_BROADCAST_TOWER'),
  ('BUILDING_RU_NATIONAL_VAULT', 'TXT_KEY_BUILDING_RU_NATIONAL_VAULT', 'TXT_KEY_BUILDING_RU_NATIONAL_VAULT_HELP', 1, 'TECH_INTERNET', 1, 1, 'BUILDINGCLASS_NATIONAL_TREASURY');

-- Dummy building for temporary city debuffs (cyberstorm) and intercept buffs
INSERT INTO Buildings
  (Type, Description, Help, Cost, PrereqTech, NeverCapture, NukeImmune, BuildingClass, GreatWorkCount)
VALUES
  ('BUILDING_RU_DUMMY_TEMP', 'TXT_KEY_BUILDING_RU_DUMMY_TEMP', 'TXT_KEY_BUILDING_RU_DUMMY_TEMP_HELP', -1, 'TECH_RADIO', 1, 1, 'BUILDINGCLASS_MONUMENT', -1);
