-- Shadow policies to mirror AL levels (fallback persistence)
INSERT INTO Policies (Type, Description, Help)
VALUES
  ('POLICY_RU_AL1','TXT_KEY_POLICY_RU_AL1','TXT_KEY_POLICY_RU_AL_HELP'),
  ('POLICY_RU_AL2','TXT_KEY_POLICY_RU_AL2','TXT_KEY_POLICY_RU_AL_HELP'),
  ('POLICY_RU_AL3','TXT_KEY_POLICY_RU_AL3','TXT_KEY_POLICY_RU_AL_HELP'),
  ('POLICY_RU_AL4','TXT_KEY_POLICY_RU_AL4','TXT_KEY_POLICY_RU_AL_HELP'),
  ('POLICY_RU_AL5','TXT_KEY_POLICY_RU_AL5','TXT_KEY_POLICY_RU_AL_HELP');
